### ISSUE TITLE
Tarea Infografia Matematicas discretas (Hugo Ivan)

### ISSUE THREAD

**Issue by Ivan-PerezZ** [SistemasTecTlaxiaco/infografia-Ivan-PerezZ#1]
[Infografia_Hugo Ivan.pdf](https://github.com/user-attachments/files/16821439/Infografia_Hugo.Ivan.pdf)

**Comment by Ivan-PerezZ** [comment]
[Uploading Infografia, Matematicas discretas (Hugo Ivan Perez Sailva) 1AS.pdf

**Comment by LeinnaMora** [comment]
Redacción y Ortografía:  12/14

Exposición de ideas Centrales: 9/16

Organización de ideas Centrales: 12/14

Uso de Imágenes y Colores: 14/14

Presentación Visual: 12/14

Referencias: 4/14

Presentación: 12/14

Calificación Final: 15/20

**Comment by josealfredo79** [comment]
revisado..
